### PR TITLE
Fix some typos. Correct imports. Refactor data layers

### PR DESCRIPTION
**Pull request by elezar**
I have made the following changes:
* Fix some typos
* Correct imports 
* Refactor data layers (the batch loader is now used for both the sync and async classes to remove duplication).
* Apply PEP8 formatting

### CODE REVIEW

**Comment by beijbom** [comment]
Hey Evan,

**Comment by beijbom** [comment]
Sorry, I didn't mean to close it yet! Like I said, there are pros and cons with both versions. Let's see what other folks think.

**Comment by elezar** [comment]
@beijbom I have made the required edits to the data layers. I hope that these are better now.

**Comment by beijbom** [comment]
thanks Evan, looks good! I talked to Shelhamer yesterday, and I'm going to make a final pass today and then finally merge it. Thanks again for your help.

**Pull request merged**
